### ISSUE TITLE
All -loader should be in devDependencies

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#1]
https://github.com/trust2065/orchard/blob/fa86e2e1ed8194d0897ee7e8eee93ad48736457b/package.json#L19

**Comment by trust2065** [comment]
Agree. 
I found a post that explain the reason.

https://stackoverflow.com/questions/40143357/do-you-put-babel-and-webpack-in-devdependencies-or-dependencies

The babel and webpack packages will go into the devDependencies section because these packages are used in when transpiling and bundle-ing your code into vanilla javascript in the bundle.js & etc file(s).

In production you will run your code off the bundle.js build/generated code will not require these dependencies anymore.
