### ISSUE TITLE
Check if you can use CSS Grid for the images layout

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#12]
You described the difficulty of making the images layout. Try CSS Grid. It seems that their browser support standard is ok for this.

https://www.w3schools.com/css/css_grid.asp
https://css-tricks.com/snippets/css/complete-guide-grid/

**Comment by trust2065** [comment]
**I would like to use `flexbox` to achieve it once that is not too hard.**


Before talk with you, I was thinking of the image size may various since we might get image from CMS as well. My thought is keep image container in place and use properties on image such as `object-fit`, `width`, `height`. And that make it a bit complicate on css as I told you.
Anyway, it turns out with right layout in my mind but the image would get cut, therefore, I would assume the image size sustain and just layout with `flexbox`.




Note: this indicate my origin thought
img1 and img2 align on top line
img1 and img3 align on bottom line
![image](https://user-images.githubusercontent.com/13488449/61591301-91f55100-ac08-11e9-919b-acaa26220d56.png)
