### ISSUE TITLE
Style not ready before rendering

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#24]
With the mobile network, I can see both your GitHub page and Netlify page render without proper styling in the first glance. It's a poor user experience.  Usually, it's caused by CSS injection timing. Also, it causes slow UI rendering when you have a complicated web page. 

Can you find a solution for this?

![image](https://user-images.githubusercontent.com/136648/61685673-0e467c00-ad50-11e9-9f1c-8234020b3ac7.png)

**Comment by trust2065** [comment]
Fixed by PR #19
![image](https://user-images.githubusercontent.com/13488449/62042470-8675db80-b241-11e9-829f-777dbffdb298.png)

https://github.com/trust2065/orchard/pull/19/files#diff-11e9f7f953edc64ba14b0cc350ae7b9d

CSS style file is load before body load now, therefore fix the issue.
Correct me if I misunderstand the concept. 
https://choco-orchard.netlify.com/
