### ISSUE TITLE
User behaviours

### ISSUE THREAD

**Issue by josephj** [trust2065/orchard#26]
The following is from the spec

1. Section: Answer your body's needs
    * These items should be links to new pages
1. Section: All the latest
    * Each image in this section should display in a modal on click

* What's your interpretation for the spec?
* Do they provide the link destination in your Invision mockup? 
* Should you place the text into the modal as well so that it's suitable to see the same modal when user click the "READ MORE?"

**Comment by trust2065** [comment]
- What's your interpretation for the spec? (This items should be links to new pages)
Should be a detail page for it. 
I guess they may want to test designing skill through new pages. But with more content provided, I don't have too much to do!?
On the first try I simply put a link to google search page, I thought it just a test for using `<a>` tag.

- Do they provide the link destination in your Invision mockup?
    - I can't find any relative link
![image](https://user-images.githubusercontent.com/13488449/62044772-166a5400-b247-11e9-92c2-7a3986a922ea.png)

- Should you place the text into the modal as well so that it's suitable to see the same modal when user click the "READ MORE?"
    - Absolutely

**Comment by josephj** [comment]
Header/Title shouldn't be linkable in my opinion. The image should have links instead.

If they don't provide any information, just link to any page which is relevant to the content user clicks

**Comment by trust2065** [comment]
> Not sure what are you talking about. It doesn't have "READ MORE" thing here. Maybe you mix Section 1 and 2 together?
I feel a new page for image should include more information. Otherwise there is no too much meaning for me to have a new page with information you already had.
